version: 0.2

env:
  variables:
    APP_VERSION: BIGV1.0

phases:
  install:
    runtime-versions:
      java: 11
  pre_build:
    commands:
      - echo Entered the pre-build phase...
      - which java
      - java -version
      - echo "Setting JAVA_HOME environment variable"
      - export JAVA_HOME=/usr/lib/jvm/java-11
      - export PATH=$JAVA_HOME/bin:$PATH
      - mvn --version
      - mvn clean
      - aws --version
      - REPOSITORY_URI=513461903764.dkr.ecr.us-west-2.amazonaws.com/cicd_sample_app_5_ecr
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Setting application version to $APP_VERSION"
      - ls -l
      - pwd
  build:
    commands:
      - echo Entered the build phase...
      - mvn package
  post_build:
    commands:
      - echo Entered the post-build phase...
      - mvn test
      - mvn integration-test
      - printf '[{"name":"my-spring-boot-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > target/imagedefinitions.json
      - cat target/imagedefinitions.json
      - chmod 644 target/imagedefinitions.json
      - ls -l target
      - pwd

artifacts:
  files:
    - target/*.jar
    - imagedefinitions.json
  base-directory: target

cache:
  paths:
    - '/root/.m2/**/*'