version: 0.2

phases:
  install:
    runtime-versions:
      java: 11
  pre_build:
    commands:
      - echo Entered the pre-build phase...
      - which java
      - java -version
      - echo "Setting JAVA_HOME environment variable"
      - export JAVA_HOME=/usr/lib/jvm/java-11
      - export PATH=$JAVA_HOME/bin:$PATH
      - mvn --version
      - mvn clean
  build:
    commands:
      - echo Entered the build phase...
      - mvn package
  post_build:
    commands:
      - echo Entered the post-build phase...
      - mvn test
      - mvn integration-test

artifacts:
  files:
    - target/*.jar
  base-directory: target

cache:
  paths:
    - '/root/.m2/**/*'