version: 0.2

phases:
  install:
    runtime-versions:
      java: 11
  pre_build:
    commands:
      - echo Entered the pre-build phase...
      - which java
      - java -version
      - echo "Setting JAVA_HOME environment variable"
      - export JAVA_HOME=/usr/lib/jvm/java-11
      - export PATH=$JAVA_HOME/bin:$PATH
      - mvn --version
      - mvn clean
      # ECR integration
      - aws --version
      - REPOSITORY_URI=${ECR_REPO}
      - echo Logging in to Amazon ECR.....
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Entered the build phase...
      - mvn install
      - docker build --platform linux/amd64 -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker push $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Entered the post-build phase...
      - mvn test
      - mvn integration-test
      - printf '[{"name":"my-spring-boot-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - Dockerfile
    - target/*.jar
    - imagedefinitions.json
  base-directory: .

cache:
  paths:
    - '/root/.m2/**/*'